# Generated by Django 4.2.13 on 2024-05-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('framework', models.CharField(max_length=20)),
                ('plan_type', models.CharField(max_length=20)),
                ('database_type', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_vars', to='app_details.appdetails')),
            ],
        ),
    ]
